### ISSUE TITLE
Tool didn't help us - need to ensure I ran correctly

### ISSUE THREAD

**Issue by SteveDevOps** [imotov/elasticsearch-snapshot-cleanup#7]
Greetings, 
I am in triage mode with a production 7 node cluster plus separate 2 node marvel cluster for logging and need some suggestions. Our snapshot processing is broken due to an orphaned snapshot stuck in Abort. We are running ES 1.4.2 on CentOS 6.8 64bit.

The cluster allows me to specify new repos, but won't let me kick off a new snapshot to new or old repo. We decomm'ed a machine that had original repo and didn't realize snapshot was in middle of write.

Looking for suggestions. Tried your tool and got it up and running on a machine near to cluster. Results of tool were that it could not find any metadata for running snapshot. Came back null.

```
lasticsearch-snapshot-cleanup-1.4.4.2]# bin/cleanup 
Setting ES_HOME as /root/elasticsearch-snapshot-cleanup-1.4.4.2
OpenJDK 64-Bit Server VM warning: If the number of processors is expected to increase from one, then you should configure the number of parallel GC threads appropriately using -XX:ParallelGCThreads=N
[2017-06-02 04:45:22,984][INFO ][org.elasticsearch.node   ] [snapcleaner] version[1.4.2], pid[30371], build[927caff/2014-12-16T14:11:12Z]
[2017-06-02 04:45:22,984][INFO ][org.elasticsearch.node   ] [snapcleaner] initializing ...
[2017-06-02 04:45:22,987][INFO ][org.elasticsearch.plugins] [snapcleaner] loaded [], sites []
[2017-06-02 04:45:24,961][INFO ][org.elasticsearch.node   ] [snapcleaner] initialized
[2017-06-02 04:45:24,961][INFO ][org.elasticsearch.node   ] [snapcleaner] starting ...
[2017-06-02 04:45:25,111][INFO ][org.elasticsearch.transport] [snapcleaner] bound_address {inet[/10.190.215.76:9300]}, publish_address {inet[/10.190.215.76:9300]}
[2017-06-02 04:45:25,130][INFO ][org.elasticsearch.discovery] [snapcleaner] prodsearch/EaAttTRJQt-M7-oM2wwMdA
[2017-06-02 04:45:55,130][WARN ][org.elasticsearch.discovery] [snapcleaner] waited for 30s and no initial state was set by the discovery
[2017-06-02 04:45:55,134][INFO ][org.elasticsearch.http   ] [snapcleaner] bound_address {inet[/10.190.215.76:9200]}, publish_address {inet[/10.190.215.76:9200]}
[2017-06-02 04:45:55,134][INFO ][org.elasticsearch.node   ] [snapcleaner] started
[2017-06-02 04:45:55,142][INFO ][org.elasticsearch.org.motovs.elasticsearch.snapshots.AbortedSnapshotCleaner] No snapshots found, snapshots metadata is null
[2017-06-02 04:45:55,142][INFO ][org.elasticsearch.node   ] [snapcleaner] stopping ...
[2017-06-02 04:45:55,153][INFO ][org.elasticsearch.node   ] [snapcleaner] stopped
[2017-06-02 04:45:55,153][INFO ][org.elasticsearch.node   ] [snapcleaner] closing ...
[2017-06-02 04:45:55,159][INFO ][org.elasticsearch.node   ] [snapcleaner] closed

```

When we try to kick off a new snapshot, even to new repo:

```
./testsnap.sh
{"error":"RemoteTransportException[[prodsearch3][inet[/10.190.215.15:9300]][cluster:admin/snapshot/create]]; nested: ConcurrentSnapshotExecutionException[[es-backups-2017:juntest] a snapshot is already running]; ","status":503}
```

checking status:
```
curl -XGET http://xxx-pes-01:9200/_snapshot/_status
{"snapshots":[{"snapshot":"olopen1-20170525133011","repository":"es-backups","state":"ABORTED","shards_stats":{"initializing":0,"started":0,"finalizing":0,"done":0,"failed":0,"total":0},"stats":{"number_of_files":0,"processed_files":0,"total_size_in_bytes":0,"processed_size_in_bytes":0,"start_time_in_millis":0,"time_in_millis":0},"indices":{}}]}[root@xxx-pmq-01 elasticsearch-snapshot-cleanup-1.4.4.2]# curl -XGET http://xxx-pes-01:9200/_snapshot/_status?pretty
{
  "snapshots" : [ {
    "snapshot" : "olopen1-20170525133011",
    "repository" : "es-backups",
    "state" : "ABORTED",
    "shards_stats" : {
      "initializing" : 0,
      "started" : 0,
      "finalizing" : 0,
      "done" : 0,
      "failed" : 0,
      "total" : 0
    },
    "stats" : {
      "number_of_files" : 0,
      "processed_files" : 0,
      "total_size_in_bytes" : 0,
      "processed_size_in_bytes" : 0,
      "start_time_in_millis" : 0,
      "time_in_millis" : 0
    },
    "indices" : { }
  } ]
}
```

I used our ES config on your tool's -- tweaking to not allow data or master roles.. assuming that is correct/works. Any other suggestions? I have tried restarts, no change. Need help.

**Comment by imotov** [comment]
> I used our ES config on your tool's -- tweaking to not allow data or master roles.. assuming that is correct/works. 

You don't need to tweak data and master roles. The cleanup tool starts as a [client node](https://github.com/imotov/elasticsearch-snapshot-cleanup/blob/master/src/main/java/org/motovs/elasticsearch/snapshots/AbortedSnapshotCleaner.java#L46) regardless the configuration. You just need to specify correct cluster name and discovery settings so it can connect to your cluster. Unfortunately, it doesn't look like it was able to connect to your cluster. Can you check the log files on the master node to see that the client in the cleanup tool actually connects to the cluster?

**Comment by SteveDevOps** [comment]
config we used on your tool that matches rest of cluster accept for minor tweaks/IPs, etc:

```---
bootstrap: 
  mlockall: true
cluster: 
  name: prodsearch
  routing: 
    allocation: 
      awareness: 
        attributes: rack
discovery: 
  zen: 
    minimum_master_nodes: 5
    ping: 
      multicast: 
        enabled: false
      timeout: 30s
      unicast: 
        hosts: ["10.190.215.13","10.190.215.14","10.190.215.15","10.190.215.16","10.190.215.17","10.190.215.18","10.190.215.75"]
gateway: 
  expected_nodes: 7
  recover_after_nodes: 5
  recover_after_time: 5m
  type: local
http: 
  compression: true
  cors: 
    enabled: true
  port: 9200
indices: 
  recovery: 
    max_bytes_per_sec: 50mb
marvel: 
  agent: 
    exporter: 
      es: 
        hosts: ["xxx-peslog-01:9200","xxx-peslog-02:9200"]
network: 
  host: 10.190.215.76
node: 
  data: false
  master: false
  name: snapcleaner
  rack: main
path: 
  data: /root/elasticsearch-snapshot-cleanup-1.4.4.2/data/snapcleaner
  logs: /root/elasticsearch-snapshot-cleanup-1.4.4.2/log/snapcleaner
threadpool: 
  bulk: 
    queue_size: 300
```

**Comment by imotov** [comment]
Can you remove everything from config file except:
```
cluster.name: "prodsearch"
network.host: "10.190.215.76"
discovery.zen.ping.multicast.enabled: false
discovery.zen.ping.unicast.hosts: ["10.190.215.13","10.190.215.14","10.190.215.15","10.190.215.16","10.190.215.17","10.190.215.18","10.190.215.75"]
```
Is `10.190.215.76` indeed the IP address of the machine you are running the tool?

Do you see this node appearing in the master logs?

**Comment by SteveDevOps** [comment]
ok ty, will cleanup config.. 
yes that is IP of tool.

but first tried it again using my verbose config while watching logs. Got error and had to ctrl-c it this time..
I get on tool server:

```
./cleanup 
Setting ES_HOME as /root/elasticsearch-snapshot-cleanup-1.4.4.2
OpenJDK 64-Bit Server VM warning: If the number of processors is expected to increase from one, then you should configure the number of parallel GC threads appropriately using -XX:ParallelGCThreads=N
[2017-06-02 11:12:54,841][INFO ][org.elasticsearch.node   ] [snapcleaner] version[1.4.2], pid[21893], build[927caff/2014-12-16T14:11:12Z]
[2017-06-02 11:12:54,841][INFO ][org.elasticsearch.node   ] [snapcleaner] initializing ...
[2017-06-02 11:12:54,845][INFO ][org.elasticsearch.plugins] [snapcleaner] loaded [], sites []
[2017-06-02 11:12:56,871][INFO ][org.elasticsearch.node   ] [snapcleaner] initialized
[2017-06-02 11:12:56,889][INFO ][org.elasticsearch.node   ] [snapcleaner] starting ...
[2017-06-02 11:12:56,993][INFO ][org.elasticsearch.transport] [snapcleaner] bound_address {inet[/10.190.215.76:9300]}, publish_address {inet[/10.190.215.76:9300]}
[2017-06-02 11:12:57,000][INFO ][org.elasticsearch.discovery] [snapcleaner] prodsearch/d0edimdfTgyJG7iEvyxjfg
[2017-06-02 11:13:27,000][WARN ][org.elasticsearch.discovery] [snapcleaner] waited for 30s and no initial state was set by the discovery
[2017-06-02 11:13:27,004][INFO ][org.elasticsearch.http   ] [snapcleaner] bound_address {inet[/10.190.215.76:9200]}, publish_address {inet[/10.190.215.76:9200]}
[2017-06-02 11:13:27,004][INFO ][org.elasticsearch.node   ] [snapcleaner] started
Exception in thread "main" org.elasticsearch.ElasticsearchException: Failed to load logging configuration
	at org.elasticsearch.common.logging.log4j.LogConfigurator.resolveConfig(LogConfigurator.java:135)
	at org.elasticsearch.common.logging.log4j.LogConfigurator.configure(LogConfigurator.java:85)
	at org.motovs.elasticsearch.snapshots.AbortedSnapshotCleaner.<init>(AbortedSnapshotCleaner.java:51)
	at org.motovs.elasticsearch.snapshots.AbortedSnapshotCleaner.<init>(AbortedSnapshotCleaner.java:46)
	at org.motovs.elasticsearch.snapshots.AbortedSnapshotCleaner.main(AbortedSnapshotCleaner.java:31)
Caused by: java.nio.file.NoSuchFileException: /root/elasticsearch-snapshot-cleanup-1.4.4.2/bin/config
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at java.nio.file.Files.readAttributes(Files.java:1737)
	at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:225)
	at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322)
	at java.nio.file.Files.walkFileTree(Files.java:2662)
	at org.elasticsearch.common.logging.log4j.LogConfigurator.resolveConfig(LogConfigurator.java:119)
	... 4 more
[2017-06-02 11:13:27,350][INFO ][org.elasticsearch.cluster.service] [snapcleaner] detected_master [prodsearch3][B3EMI3hjQYyur8sDIW17Lg][xxx-pes-03.inetuhosted.net][inet[/10.190.215.15:9300]]{rack=main, master=true}, added {[prodsearch5][jvOLKHs2T_mfJa4jxnNB5A][xxx-pes-05.inetuhosted.net][inet[/10.190.215.17:9300]]{rack=main, master=true},[prodsearch1][CnJJqx33SqGGRHBwEDPsog][xxx-pes-01.inetuhosted.net][inet[/10.190.215.13:9300]]{rack=main, master=true},[prodsearch4][UWtNglBFRUGB9lYguiRitA][xxx-pes-04.inetuhosted.net][inet[/10.190.215.16:9300]]{rack=main, master=true},[prodsearch7][rHfH4FmPTRyNLj4GDdiLzg][xxx-pes-07.inetuhosted.net][inet[/10.190.215.75:9300]]{rack=main, master=true},[prodsearch6][kiJSjq2_Sm2dpVMACGTk_Q][xxx-pes-06.inetuhosted.net][inet[/10.190.215.18:9300]]{rack=main, master=true},[prodsearch3][B3EMI3hjQYyur8sDIW17Lg][xxx-pes-03.inetuhosted.net][inet[/10.190.215.15:9300]]{rack=main, master=true},[prodsearch2][l5XQtIDxRlat7w9QC-OnWQ][xxx-pes-02.inetuhosted.net][inet[/10.190.215.14:9300]]{rack=main, master=true},}, reason: zen-disco-receive(from master [[prodsearch3][B3EMI3hjQYyur8sDIW17Lg][xxx-pes-03.inetuhosted.net][inet[/10.190.215.15:9300]]{rack=main, master=true}])
```

and on master node tailing log:

```
[2017-06-02 11:13:27,113][INFO ][cluster.service          ] [prodsearch3] added {[snapcleaner][d0edimdfTgyJG7iEvyxjfg][xxx-pmq-01.abe01.xxx.net][inet[/10.190.215.76:9300]]{client=true, rack=main, data=false, master=false},}, reason: zen-disco-receive(join from node[[snapcleaner][d0edimdfTgyJG7iEvyxjfg][xxx-pmq-01.abe01.xxx.net][inet[/10.190.215.76:9300]]{client=true, rack=main, data=false, master=false}])
[2017-06-02 11:14:47,572][INFO ][cluster.service          ] [prodsearch3] removed {[snapcleaner][d0edimdfTgyJG7iEvyxjfg][xxx-pmq-01.abe01.xxx.net][inet[xxx-pmq-01.abe01.xxx.net/10.190.215.76:9300]]{client=true, rack=main, data=false, master=false},}, reason: zen-disco-node_failed([snapcleaner][d0edimdfTgyJG7iEvyxjfg][xxx-pmq-01.abe01.xxx.net][inet[xxx-pmq-01.abe01.xxx.net/10.190.215.76:9300]]{client=true, rack=main, data=false, master=false}), reason transport disconnected

```

I will try reducing config now

**Comment by SteveDevOps** [comment]
YOU ROCK. simple config just worked!!! My config was complicating things. Could've sworn I tried simple first and got that same logging error you see above.. whatever, SOLVED. Apparently I missed something. Next time you are in ATL, I owe you a beer. Thx a TON for this tool.

```
bin/cleanup 
Setting ES_HOME as /root/elasticsearch-snapshot-cleanup-1.4.4.2
OpenJDK 64-Bit Server VM warning: If the number of processors is expected to increase from one, then you should configure the number of parallel GC threads appropriately using -XX:ParallelGCThreads=N
[2017-06-02 11:24:00,953][INFO ][org.elasticsearch.node   ] [Two-Gun Kid] version[1.4.2], pid[23619], build[927caff/2014-12-16T14:11:12Z]
[2017-06-02 11:24:00,953][INFO ][org.elasticsearch.node   ] [Two-Gun Kid] initializing ...
[2017-06-02 11:24:00,963][INFO ][org.elasticsearch.plugins] [Two-Gun Kid] loaded [], sites []
[2017-06-02 11:24:03,036][INFO ][org.elasticsearch.node   ] [Two-Gun Kid] initialized
[2017-06-02 11:24:03,036][INFO ][org.elasticsearch.node   ] [Two-Gun Kid] starting ...
[2017-06-02 11:24:03,158][INFO ][org.elasticsearch.transport] [Two-Gun Kid] bound_address {inet[/10.190.215.76:9300]}, publish_address {inet[/10.190.215.76:9300]}
[2017-06-02 11:24:03,250][INFO ][org.elasticsearch.discovery] [Two-Gun Kid] prodsearch/RfrXUUh8RZqtuf7efBPTyg
[2017-06-02 11:24:06,578][INFO ][org.elasticsearch.cluster.service] [Two-Gun Kid] detected_master [prodsearch3][B3EMI3hjQYyur8sDIW17Lg][xxx-pes-03.xxx.net][inet[/10.190.215.15:9300]]{rack=main, master=true}, added {[prodsearch5][jvOLKHs2T_mfJa4jxnNB5A][xxx-pes-05.xxx.net][inet[/10.190.215.17:9300]]{rack=main, master=true},[prodsearch1][CnJJqx33SqGGRHBwEDPsog][xxx-pes-01.xxx.net][inet[/10.190.215.13:9300]]{rack=main, master=true},[prodsearch4][UWtNglBFRUGB9lYguiRitA][xxx-pes-04.xxx.net][inet[/10.190.215.16:9300]]{rack=main, master=true},[prodsearch7][rHfH4FmPTRyNLj4GDdiLzg][xxx-pes-07.xxx.net][inet[/10.190.215.75:9300]]{rack=main, master=true},[prodsearch6][kiJSjq2_Sm2dpVMACGTk_Q][xxx-pes-06.xxx.net][inet[/10.190.215.18:9300]]{rack=main, master=true},[prodsearch3][B3EMI3hjQYyur8sDIW17Lg][xxx-pes-03.xxx.net][inet[/10.190.215.15:9300]]{rack=main, master=true},[prodsearch2][l5XQtIDxRlat7w9QC-OnWQ][xxx-pes-02.xxx.net][inet[/10.190.215.14:9300]]{rack=main, master=true},}, reason: zen-disco-receive(from master [[prodsearch3][B3EMI3hjQYyur8sDIW17Lg][xxx-pes-03.xxx.net][inet[/10.190.215.15:9300]]{rack=main, master=true}])
[2017-06-02 11:24:06,605][INFO ][org.elasticsearch.discovery.zen] [Two-Gun Kid] updating discovery.zen.minimum_master_nodes from [-1] to [5]
[2017-06-02 11:24:06,613][INFO ][org.elasticsearch.http   ] [Two-Gun Kid] bound_address {inet[/10.190.215.76:9200]}, publish_address {inet[/10.190.215.76:9200]}
[2017-06-02 11:24:06,613][INFO ][org.elasticsearch.node   ] [Two-Gun Kid] started
[2017-06-02 11:24:06,620][INFO ][org.elasticsearch.org.motovs.elasticsearch.snapshots.AbortedSnapshotCleaner] Processing snapshot [es-backups:olopen1-20170525133011]
[2017-06-02 11:24:06,621][INFO ][org.elasticsearch.node   ] [Two-Gun Kid] stopping ...
[2017-06-02 11:24:06,653][INFO ][org.elasticsearch.node   ] [Two-Gun Kid] stopped
[2017-06-02 11:24:06,653][INFO ][org.elasticsearch.node   ] [Two-Gun Kid] closing ...
[2017-06-02 11:24:06,656][INFO ][org.elasticsearch.node   ] [Two-Gun Kid] closed
```

I am literally dancing a jig ;) Thx for assist!
